### PR TITLE
Env configuration update to ray 1.12 standard

### PR DESCRIPTION
**Pull request by PhilippWillms**
This PR goes hand-in-hand with this [PR ](https://github.com/prosysscience/JSSEnv/pull/8) in the JSSEnv repo and contributes to fixing the issue reported in #28. Following the ray 1.12.0 guide on [Configuring Environments](https://docs.ray.io/en/latest/rllib/rllib-env.html#configuring-environments), a proper ray-compatible env registration is described in main.py. now.

### CODE REVIEW

**Comment by mf093087** [comment]
where is the description in main.py? Could you please help me. Many thanks in advance

**Comment by PhilippWillms** [comment]
> where is the description in main.py? Could you please help me. Many thanks in advance

Which description? Comparing the original files with my latest commit I did not find any deleted comment blocks or similar ...

EDIT: Kindly have a look also at the GitHub repository containing the [JSSEnv ](https://github.com/prosysscience/JSSEnv)

**Comment by mf093087** [comment]
> > where the description in main.py is? Could you please help me. Many thanks in advance
> 
> Which description? Comparing the original files with my latest commit I did not find any deleted comment blocks or similar ...
> 
> EDIT: Kindly have a look also at the GitHub repository containing the [JSSEnv ](https://github.com/prosysscience/JSSEnv)

Thanks a lot for the quick reply! Yes, I have also downloaded this [JSSEnv](https://github.com/prosysscience/JSSEnv) and tried this. However, now I want to try to train the Taillard instance as you did in this repository https://github.com/prosysscience/RL-Job-Shop-Scheduling/tree/master/JSS  .  When I try run main.py, I receive the following error:
https://github.com/prosysscience/RL-Job-Shop-Scheduling/issues/35

I registered the environment manually, but still, it didn't work..

**Comment by PhilippWillms** [comment]
Closed as outdated.

**Pull request closed without merging**
